weather/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['TIMEOUT'] = 100000
    
    # blueprint
    from weather.views import main_views, clothes_views, weather_views
    app.register_blueprint(main_views.bp)
    app.register_blueprint(clothes_views.bp)
    app.register_blueprint(weather_views.bp)

    return app

weather/views/clothes_views.py
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect

bp = Blueprint('clothes', __name__, url_prefix='/')


import requests
import json

API_key = 'a70dc2963798086f5d430b6af4a55004'
city_name = 'Seoul'

URL = f"https://api.openweathermap.org/data/2.5/weather?q={city_name}&appid={API_key}&units=metric"

row_data = requests.get(URL)
current_weather = json.loads(row_data.text)


@bp.route('/clothes')
def hello_clothes():
    
    temp = current_weather['main']['temp']
    weather = current_weather['weather'][0]['main']
    
    if temp >= 28:
        answer = "민소매, 반팔, 반바지, 원피스"
    elif temp >= 23:
        answer = "반팔, 얇은 셔츠, 반바지, 면바지"
    elif temp >= 20:
        answer = "얇은 가디건, 반팔, 면바지, 청바지"
    elif temp >= 17:
        answer = "얇은 니트, 맨투맨, 가디건, 청바지"
    elif temp >= 12:
        answer = "자켓, 가디건, 야상, 스타킹, 청바지, 면바지"
    elif temp >= 9:
        answer = "자켓, 트렌치코트, 야상, 니트, 청바지, 스타킹"
    elif temp >= 5:
        answer = "코트, 가죽자켓, 히트텍, 니트, 레깅스"
    else:
        answer = "패딩, 두꺼운 코트, 목도리, 기모제품"
    
    return render_template('clothes.html', temp=temp, weather=weather, answer=answer)

weather/views/main_views.py
from flask import Blueprint, url_for, render_template
from werkzeug.utils import redirect

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def hello_weather():
    return render_template('main.html')

weather/views/weather_views.py
from flask import Blueprint, url_for, render_template, request
from werkzeug.utils import redirect
import pickle
import pandas as pd
import traceback
import time

# 기온 예측
with open('/Users/yerin/AIB/section4/project/PART2_Modeling/model_ta.pkl','rb') as pickle_file:
    model_ta = pickle.load(pickle_file)
    
# 강수 예측
# 0 = 많은 비, 1 = 비 안옴, 2 = 비
with open('/Users/yerin/AIB/section4/project/PART2_Modeling/model_rn.pkl','rb') as pickle_file:
    model_rn = pickle.load(pickle_file)

# 눈 예측
# 0 = 눈, 1 = 눈 없음
with open('/Users/yerin/AIB/section4/project/PART2_Modeling/model_sn.pkl','rb') as pickle_file:
    model_sn = pickle.load(pickle_file)
    
bp = Blueprint('weather', __name__, url_prefix='/')

@bp.route('/weather')
def hello_weather():
    return render_template('weather.html')

@bp.route('/weather/result', methods=['POST'])
def result():
    
    month = None
    day = None
    
    data = pd.DataFrame({'month':[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        'day':[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        'time':[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]})
    
    month = int(request.form.get("month"))
    day = int(request.form.get("day"))
    
    # 모델 예측을 위한 dataframe
    data['month'] = month
    data['day'] = day

    # 기온 예측
    pred_ta = model_ta.predict(data)
    
    # 기온 profiling
    morning = round( (sum(pred_ta[6:11]) / len(pred_ta[6:11])), 2)
    afternoon = round( (sum(pred_ta[11:17]) / len(pred_ta[11:17])), 2)
    evening = round( (sum(pred_ta[17:]) / len(pred_ta[17:])), 2)
    dawn = round( (sum(pred_ta[:5]) / len(pred_ta[:5])), 2)
    
    # 강수, 적설 예측을 위한 dataframe
    data['ta'] = pred_ta
    
    pred_rn = []
    pred_sn = []
    
    # 겨울이 아닐 경우 강수 예측, 겨울일 경우 적설 예측
    if (12 > month > 2):
        
        pred_rn = list(model_rn.predict(data))
        rn_mor = pred_rn[6:11]
        rn_aft = pred_rn[11:17]
        rn_eve = pred_rn[17:]
        rn_dawn = pred_rn[:5]
        
        if 0 in rn_mor:
            rn_mor = "오전에는 많은 비가 올 것으로 예상됩니다."
        elif 2 in rn_mor:
            rn_mor = "오전에는 비가 올 것으로 예상됩니다."
        else:
            rn_mor = "오전에는 비가 오지 않을 것으로 예상됩니다."
        
        if 0 in rn_aft:
            rn_aft = "오후에는 많은 비가 올 것으로 예상됩니다."
        elif 2 in rn_aft:
            rn_aft = "오후에는 비가 올 것으로 예상됩니다."
        else:
            rn_aft = "오후에는 비가 오지 않을 것으로 예상됩니다."
            
        if 0 in rn_eve:
            rn_eve = "저녁에는 많은 비가 올 것으로 예상됩니다."
        elif 2 in rn_eve:
            rn_eve = "저녁에는 비가 올 것으로 예상됩니다."
        else:
            rn_eve = "저녁에는 비가 오지 않을 것으로 예상됩니다."

        if 0 in rn_dawn:
            rn_dawn = "새벽에는 많은 비가 올 것으로 예상됩니다."
        elif 2 in rn_dawn:
            rn_dawn = "새벽에는 비가 올 것으로 예상됩니다."
        else:
            rn_dawn = "새벽에는 비가 오지 않을 것으로 예상됩니다."
        
        sn_mor = []
        sn_aft = []
        sn_eve = []
        sn_dawn = []
        pred_sn = []

    elif (month < 3) or (month > 11):
        
        pred_sn = model_sn.predict(data)
        sn_mor = pred_sn[6:11]
        sn_aft = pred_sn[11:17]
        sn_eve = pred_sn[17:]
        sn_dawn = pred_sn[:5]
        
        if 1 in sn_mor:
            sn_mor = "오전에는 눈이 올 것으로 예상됩니다."
        else:
            sn_mor = "오전에는 눈이 오지 않을 것으로 예상됩니다."
        
        if 1 in sn_aft:
            sn_aft = "오후에는 눈이 올 것으로 예상됩니다."
        else:
            sn_aft = "오후에는 눈이 오지 않을 것으로 예상됩니다."
            
        if 1 in sn_eve:
            sn_eve = "저녁에는 눈이 올 것으로 예상됩니다."
        else:
            sn_eve = "저녁에는 눈이 오지 않을 것으로 예상됩니다."

        if 1 in sn_dawn:
            sn_dawn = "새벽에는 눈이 올 것으로 예상됩니다."
        else:
            sn_dawn = "새벽에는 눈이 오지 않을 것으로 예상됩니다."
        
        rn_mor = []
        rn_aft = []
        rn_eve = []
        rn_dawn = []
        pred_rn = []
        
    else:
        return "error"

    return render_template('weather_result.html', month=month, day=day, 
                           morning=morning, afternoon=afternoon, evening=evening, dawn=dawn,
                           rn_mor=rn_mor, rn_aft=rn_aft, rn_eve=rn_eve, rn_dawn=rn_dawn,
                           sn_mor=sn_mor, sn_aft=sn_aft, sn_eve=sn_eve, sn_dawn=sn_dawn,
                           pred_rn=pred_rn, pred_sn=pred_sn)
    

weather/templates/clothes.html
<style>
  
    .button1 {
        background: linear-gradient(to right, #5fc3e4, #E6E6FA);
        box-shadow: #708090;
        width: 300px;
        height: 80px;
        font-size: 1em;
        font-weight: 400;
        font-family: "Helvetica", "Arial", sans-serif;
        border-radius: 4px;
        cursor: pointer;
        appearance: none;
        border: solid 1px #191970;
        color: #000000;
        margin-bottom: 20px;
        font-size: 20px;
        border-radius: 15px;
      }

      .outer {
        text-align: center;
        position: absolute;
        left: 45%;
        top: 50%;
        margin-left: -150px;
        margin-top: -210px;
      }

      .title {text-align: center;}
    
</style>

<div class = "outer">
    <body style= "background: linear-gradient(to right, #E6E6FA, #5fc3e4);">

    <hr style= "height: 1px; background-color: #191970;">
    <h1 class="title"> 오늘 기온에 따른 옷 추천! </h1>
    <hr style= "height: 2px; background-color: #191970;">
    <p>현재 기온: {{temp}}℃</p>
    <p>현재 날씨: {{weather}}</p>
    <hr style= "height: 0.5px; background-color: #191970;">
    <p>현재 날씨에 적합한 외출복은 {{answer}} 입니다!</p>
    {% if weather == "rain" %}
        <p>지금은 비가 오니 우산을 준비하세요!</p>
    {% endif %}
    <br>
    <br>

    <p>28℃ 이상: 민소매, 반팔, 반바지, 원피스</p>
    <p>27℃~23℃: 반팔, 얇은 셔츠, 반바지, 면바지</p>
    <p>22℃~20℃: 얇은 가디건, 반팔, 면바지, 청바지</p>
    <p>19℃~17℃: 얇은 니트, 맨투맨, 가디건, 청바지</p>
    <p>16℃~12℃: 자켓, 가디건, 야상, 스타킹, 청바지, 면바지</p>
    <p>11℃~9℃: 자켓, 트렌치코트, 야상, 니트, 청바지, 스타킹</p>
    <p>8℃~5℃: 코트, 가죽자켓, 히트텍, 니트, 레깅스</p>
    <p>4℃~: 패딩, 두꺼운 코트, 목도리, 기모제품</p>

    <br>
    <br>
    <br>

        <div style="button1">
            <button class="button1"
            type="button" onClick="location.href='../'"> 되돌아가기
            </button>
            <br>
            <br>
            <br>
            <br>
        </div>
    </body>
</div>

weather/templates/main.html
<style>
  
    .button1 {
        background: linear-gradient(to right, #5fc3e4, #E6E6FA);
        box-shadow: #708090;
        width: 300px;
        height: 80px;
        font-size: 1em;
        font-weight: 400;
        font-family: "Helvetica", "Arial", sans-serif;
        border-radius: 4px;
        cursor: pointer;
        appearance: none;
        border: solid 1px #191970;
        color: #000000;
        margin-bottom: 20px;
        font-size: 20px;
        border-radius: 15px;
      }

      .outer {
        text-align: center;
        position: absolute;
        left: 50%;
        top: 50%;
        margin-left: -150px;
        margin-top: -140px;
      }

      .title {text-align: center;}
    
</style>

<body style= "background: linear-gradient(to right, #E6E6FA, #5fc3e4);">

<hr style= "height: 1px; background-color: #191970;">
<h1 class="title"> 나에게 필요한 기상청 </h1>
<hr style= "height: 2px; background-color: #191970;">

<div class = "outer">
<!-- weather -->
    <h2> 그 날의 날씨는 어떨까?</h2>
    <button class="button1"
        type="button" onClick="location.href='weather'"> 날씨 검색하기
    </button>

<!-- clothes -->
    <h2> 오늘은 무슨 옷을 입을까? </h2>
    <button class="button1"
        type="button" onClick="location.href='clothes'"> 오늘 날씨에 맞는 옷 추천받기
    </button>

<!-- dashboard-

    <h2> 날씨 분석 바로가기 </h2>
    <button class="button1"
        type="button" onClick="location.href='dash'"> 대시보드
    </button>
</div> -->

</body>

weather/templates/weather.html
<head>
<style>
  
    .button1 {
        background: linear-gradient(to right, #5fc3e4, #E6E6FA);
        box-shadow: #708090;
        width: 140px;
        height: 50px;
        font-size: 1em;
        font-weight: 400;
        font-family: "Helvetica", "Arial", sans-serif;
        border-radius: 4px;
        cursor: pointer;
        appearance: none;
        border: solid 1px #191970;
        color: #000000;
        margin-bottom: 20px;
        font-size: 20px;
        border-radius: 15px;
      }


    .pl{
        width: 200px;
        border: 1px solid #C4C4C4;
        box-sizing: border-box;
        border-radius: 10px;
        padding: 12px 13px;
        font-family: 'Roboto';
        font-style: normal;
        font-weight: 400;
        font-size: 14px;
        line-height: 16px;
        }

      .outer {
        text-align: center;
        position: absolute;
        left: 55%;
        top: 50%;
        margin-left: -180px;
        margin-top: -210px;
      }

      .title {text-align: center;}
    
</style>
</head>


<body style= "background: linear-gradient(to right, #E6E6FA, #5fc3e4);">


<div class = "outer">

<hr style= "height: 1px; background-color: #191970;">
<h1>weather</h1>
<p>날짜를 선택하세요!</p>
<hr style= "height: 1px; background-color: #191970;">

<form action="{{ url_for('weather.result') }}" method="post">
    <div class = "input">
    <br>
    <h4> MONTH(월) </h4>
    <select class="pl" name="month" >
        <option value=1>1월</option>
        <option value=2>2월</option>
        <option value=3>3월</option>
        <option value=4>4월</option>
        <option value=5>5월</option>
        <option value=6>6월</option>
        <option value=7>7월</option>
        <option value=8>8월</option>
        <option value=9>9월</option>
        <option value=10>10월</option>
        <option value=11>11월</option>
        <option value=12>12월</option>
    </select>

    <h4> DAY(일) </h4>
    <select class="pl" name="day">
        <option value=1>1일</option>
        <option value=2>2일</option>
        <option value=3>3일</option>
        <option value=4>4일</option>
        <option value=5>5일</option>
        <option value=6>6일</option>
        <option value=7>7일</option>
        <option value=8>8일</option>
        <option value=9>9일</option>
        <option value=10>10일</option>
        <option value=11>11일</option>
        <option value=12>12일</option>
        <option value=13>13일</option>
        <option value=14>14일</option>
        <option value=15>15일</option>
        <option value=16>16일</option>
        <option value=17>17일</option>
        <option value=18>18일</option>
        <option value=19>19일</option>
        <option value=20>20일</option>
        <option value=21>21일</option>
        <option value=22>22일</option>
        <option value=23>23일</option>
        <option value=24>24일</option>  
        <option value=25>25일</option>
        <option value=26>26일</option>
        <option value=27>27일</option>
        <option value=28>28일</option>
        <option value=29>29일</option>
        <option value=30>30일</option>
        <option value=31>31일</option>                        
    </select>
</div>

<br>
<br>
<br>
<br>
<div class = "submit">
    <button class="button1"
        type="submit"> 조회
    </button>
</div>
</form>

<div style="button1">
    <button class="button1"
    type="button" onClick="location.href='../'"> 되돌아가기
    </button>
    <br>
    <br>
    <br>
    <br>
</div>

</div>

</body>

weather/templates/weather_result.html
<!DOCTYPE html>
<html>
  <head>
    <style>
      
        .button1 {
            background: linear-gradient(to right, #5fc3e4, #E6E6FA);
            box-shadow: #708090;
            width: 160x;
            height: 50px;
            font-size: 1em;
            font-weight: 400;
            font-family: "Helvetica", "Arial", sans-serif;
            border-radius: 4px;
            cursor: pointer;
            appearance: none;
            border: solid 1px #191970;
            color: #000000;
            margin-bottom: 20px;
            font-size: 20px;
            border-radius: 15px;
          }
    
          .outer {
            text-align: center;
            position: absolute;
            left: 50%;
            top: 50%;
            margin-left: -150px;
            margin-top: -210px;
          }
    
          .title {text-align: center;}
        
    </style>
    </head>

  <body style= "background: linear-gradient(to right, #E6E6FA, #5fc3e4);">
  
    <div class = "outer">
  
      <hr style= "height: 1px; background-color: #191970;">
      <h1 style = "title">{{ month }}월 {{ day }}의 날씨 예보</h1>
      <hr style= "height: 1px; background-color: #191970;">
  
      <h3>=== 기온 ===</h3>
        <p>새벽 평균 기온은 {{ dawn }}℃로 예상됩니다.</p>
        <p>오전 평균 기온은 {{ morning }}℃로 예상됩니다.</p>
        <p>오후 평균 기온은 {{ afternoon }}℃로 예상됩니다.</p>
        <p>저녁 평균 기온은 {{ evening }}℃로 예상됩니다.</p>
      
        {% if pred_rn|length != 0 %}
        <h3>===강수===</h3>
        <p> {{rn_mor}} </p>
        <p> {{rn_aft}} </p>
        <p> {{rn_eve}} </p>
        <p> {{rn_dawn}} </p>
      {% endif %}
        
      {% if pred_sn|length != 0 %}
        <h3>===적설===</h3>
        <p> {{sn_mor}} </p>
        <p> {{sn_aft}} </p>
        <p> {{sn_eve}} </p>
        <p> {{sn_dawn}} </p>
      {% endif %}
      
      <br>

      {% if month == 12 and day == 25 %}
        <h1> Happy White Christmas! </h1>
      {% endif %}
      
      <br>
      <br>
      <br>

      <div style="button1">
        <button class="button1"
        type="button" onClick="location.href='../weather'"> 되돌아가기
        </button>

        <br>
        <br>

        <button class="button1"
        type="button" onClick="location.href='../../'"> 처음으로
        </button>

      </div>
    </div>
  </body>
</html>